// error-pattern: aborting due to previous error

fn main() {
    2 + +2;
}

